name: aws-codeartifact-afp-npm-login
description: Login and render .npmrc
branding:
  icon: code
  color: blue
author: Baptiste Blanchard

inputs:
  repo-name:
    description: "Repo name"
    required: true
  repo-domain:
    description: "Repo domain"
    required: true
  account-number:
    description: "AWS acct number"
    required: true
  settings-path:
    description: "path to the .npmrc file"
    required: false
    default: "/home/runner/.npmrc"
  region:
    description: "aws region"
    required: false
    default: "us-east-1"
  duration:
    default: '900'
    description: 'Duration in seconds'
    required: false
  mirror:
    default: 'false'
    description: 'Use codeartifact as mirror'
    required: false
runs:
  using: 'node20'
  main: 'dist/action/index.js'
  post: 'dist/cleanup/index.js'
      
